### ISSUE TITLE
Cloudfare Issue!

### ISSUE THREAD

**Issue by shavy4452** [MCXIV/temp8#1]
I am unable to access even i used it for the first time.

Getting message in html
Please enable cookies
Sorry you have been blocked

**Comment by shavy4452** [comment]
Ah, its cloudfare.

here is html in case you want.

<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> temp-mail.org</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">79092271feb2f3f5</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip"></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>  
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};


</script>

</body>
</html>

**Comment by mcxiv** [comment]
Indeed. I'll have a look into it. 🤔

**Comment by mcxiv** [comment]
@shavy4452 Can you have a look at the possible fix?
I tried to spam it for a bit, and I wasn't blocked.

**Comment by shavy4452** [comment]
Tried over the vps, got same thing.
http://postimg.cc/BPDPVQrB

**Comment by shavy4452** [comment]
I will try to find a solution for cloudfare but probably it's not possible.

**Comment by shavy4452** [comment]
@MCXIV cloudscraper did the work, tested your code from fix_cloudfare_antibot branch. It worked fine.
here is screenshot of it.
![image](https://user-images.githubusercontent.com/61879715/215497597-0e82e0fa-c188-4200-b2b8-f3cca2ab208d.png)

**Comment by shavy4452** [comment]
@MCXIV I would like to contribute in this project if possible.

**Comment by mcxiv** [comment]
@shavy4452 I performed a few other tests today, and I still have the problem sometimes. (Approx. 5.82% chance of getting a 403)
I will push a minor fix asap.

Please, feel free to open PR! Can't wait to have a look at it. ;)

**Comment by shavy4452** [comment]
Sorry got late, had a meeting and all. Good enough i guess now. Great job @MCXIV. I will be using this and if there would be any other issue i will raise a pr.
